### ISSUE TITLE
Improve hole detection performance

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/async-append-only-log#59]
We currently use `buf.every((x) => x === 0)` to check if a record is deleted, but there may be better (faster) ways to do that, see PR https://github.com/ssb-ngi-pointer/async-append-only-log/pull/58, especially https://github.com/ssb-ngi-pointer/async-append-only-log/pull/58#issuecomment-1067919089

**Comment by arj03** [comment]
I can work on such a module if it helps?

**Comment by staltz** [comment]
Sure!
